---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Restart elastalert2
  ansible.builtin.service:
    name: elastalert2
    state: restarted
  when: ansible_facts['service_mgr'] == 'systemd'
